### ISSUE TITLE
Would it be better to move `sign` parameter from request body to header?

### ISSUE THREAD

**Issue by Candinya** [NaturalSelectionLabs/RSS3-Hub#1]
As written in *lib/middleware/auth.ts*, it needs an extra step to strip auth parameter from request body before hashing. Would it be better to claim it in request header, and thus can use request body directly?
https://github.com/NaturalSelectionLabs/RSS3-Hub/blob/ee21b020e0fa759fff2608698106c5cb1af29e2a/lib/middleware/auth.ts#L12

Also in addition, what about use [Linked Data Signatures](https://w3c-ccg.github.io/ld-proofs/) to verify it as used in [ActivityPub's Authentication Authorization](https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization) for server-to-server communication? As for client-to-server, OAuth 2.0 or something like that should be enough. 😃

**Comment by DIYgod** [comment]
Good idea! I will move `sign` to header.

Linked Data Signatures looks complicated and I'm not sure if it's necessary.

I don't want to use OAuth 2.0 because this project will be converted to a distributed implementation in the future, so we should try to keep it simple and use logics that are also easily implemented in a distributed way.

**Comment by Candinya** [comment]
Thanks for the reply! Keep participating and looking forward to a brand new era of web 😆

**Comment by DIYgod** [comment]
Already moved `signature` from body to header b52bc7b6b6ad045be82f4d60e59d84c3488e368f
